default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: rails_media_sharing_app_development

test:
  <<: *default
  database: rails_media_sharing_app_test

production:
  <<: *default
  database: rails_media_sharing_app_production
  username: rails_media_sharing_app
  password: <%= ENV['RAILS_MEDIA_SHARING_APP_DATABASE_PASSWORD'] %>
  