environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    POSTGRES_DB: rails_netflix_app_test
web:
  build: .
  command: bundle exec rails s -b '0.0.0.0'


default: &default
adapter: postgresql
encoding: unicode
host: db
username: postgres
password: postgres
pool: 5

test:
<<: *default
database: rails_media_sharing_app_test