default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>

development:
  <<: *default
  database: rails_media_sharing_app_development

test:
  <<: *default
  database: rails_media_sharing_app_test

production:
  <<: *default
  database: rails_media_sharing_app_production
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["RAILS_MEDIA_SHARING_APP_DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
